version: '3'

services:
  mysql: 
    container_name: mysql
    image: mysql:8.4.0
    environment:
      - MYSQL_DATABASE=mymovies
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - mysql_network
    

volumes:
  mysql_volume: 

networks:
  mysql_network:
